from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

from texgraph.env import repo_root, resolve_in_repo
from texgraph.metadata import book_dirs, build_metadata

_KEYWORDS = [
    "acknowledg", "advertisement", "bibliography", "colophon", "contents",
    "dedication", "endleaf", "epigraph", "frontispiece", "illustration",
    "index", "invocation", "note", "preface", "publisher", "reading this book",
]


def _require_pdftotext() -> str:
    found = shutil.which("pdftotext")
    if not found:
        raise SystemExit("Required binary not found on PATH: pdftotext")
    return found


def _extract_text(pdf: Path, first: int, last: int) -> str:
    result = subprocess.run(
        [_require_pdftotext(), "-enc", "UTF-8", "-f", str(first), "-l", str(last), "-layout", str(pdf), "-"],
        cwd=str(repo_root()),
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        encoding="utf-8",
        errors="replace",
    )
    return result.stdout


def _hits(text: str) -> list[str]:
    found: list[str] = []
    for line in text.splitlines():
        clean = re.sub(r"\s+", " ", line).strip()
        if clean and any(kw in clean.lower() for kw in _KEYWORDS):
            found.append(clean)
    return found


def scan_book(metadata: dict[str, Any], front_pages: int, back_pages: int) -> dict[str, Any]:
    source = metadata.get("source_pdf")
    pages = metadata.get("pdf_pages")
    source_status = metadata.get("source_status")
    result: dict[str, Any] = {
        "id": metadata["id"],
        "title": metadata["title"],
        "source_pdf": source,
        "source_status": source_status,
        "pdf_pages": pages,
        "front_scan_range": None,
        "front_hits": [],
        "back_scan_range": None,
        "back_hits": [],
        "notes": [],
    }
    if source_status not in {"present", "working_source_reprint"} or not source or not isinstance(pages, int):
        result["notes"].append("source not available for scan")
        return result

    pdf = resolve_in_repo(source)
    front_last = min(front_pages, pages)
    back_first = max(1, pages - back_pages + 1)
    result["front_scan_range"] = [1, front_last]
    result["back_scan_range"] = [back_first, pages]
    result["front_hits"] = _hits(_extract_text(pdf, 1, front_last))
    result["back_hits"] = _hits(_extract_text(pdf, back_first, pages))
    return result


def _write_markdown(results: list[dict[str, Any]], output: Path) -> None:
    lines = [
        "# Source Front And Back Matter Inventory",
        "",
        "Generated by `texgraph scan`. Navigation aid for source review — not a substitute",
        "for page-image verification or transcription.",
        "",
        "| Book | Source state | Front scan range | Front matter signals | Back scan range | Back matter signals | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for item in results:
        front = "; ".join(item["front_hits"]) if item["front_hits"] else ""
        back = "; ".join(item["back_hits"]) if item["back_hits"] else ""
        notes = "; ".join(item["notes"]) if item["notes"] else ""
        lines.append(
            f"| _{item['title']}_ | {item['source_status']} | {item['front_scan_range'] or ''} | "
            f"{front} | {item['back_scan_range'] or ''} | {back} | {notes} |"
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _run(args: argparse.Namespace) -> int:
    target = resolve_in_repo(args.target)
    books = book_dirs(target)
    results = [scan_book(build_metadata(b), args.front_pages, args.back_pages) for b in books]
    _write_markdown(results, resolve_in_repo(args.output))
    print(f"books={len(results)} output={args.output}")
    return 0


def register(sub: argparse._SubParsersAction) -> None:  # type: ignore[type-arg]
    p = sub.add_parser("scan", help="Scan source PDFs for front/back matter keyword signals.")
    p.add_argument("target", help="Book, volume, or volumes directory.")
    p.add_argument("--front-pages", type=int, default=25)
    p.add_argument("--back-pages", type=int, default=12)
    p.add_argument("--output", required=True, help="Markdown output path (e.g. metadata/source_matter_inventory.md).")
    p.set_defaults(func=_run)
