#!/usr/bin/env python3
"""
skill_index.py — Enforce the skill & tool loading contract.

The agent framework loads context lazily: an agent loads only the SKILL.md and
the tool commands relevant to the classified job, never the whole skill/command
surface (see README.md § Skill & Tool Loading Contract). For that to work,
every skill must declare — in scannable frontmatter — what it is for and which
tools it touches, and a single index must map module → skills → tools so an agent
can decide what to load without opening anything.

This tool is the keeper of that contract. It:

  1. Validates every SKILL.md has the required frontmatter
     (name, description, module, tools) and that:
       - `module` resolves to a real module (or `machinery`);
       - every `tools` entry resolves to a real `texgraph` CLI command
         (extracted from cli.py) or an allow-listed framework tool.
  2. Generates / verifies the Skill & Tool Index table inside README.md,
     between the SKILL-INDEX markers.

Usage:
    python tools/skill_index.py            # validate + show drift
    python tools/skill_index.py --write     # regenerate the index
    python tools/skill_index.py --check      # CI: nonzero on any problem
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REQUIRED_FIELDS = ("name", "description", "module", "tools")

# Framework tools a skill may legitimately list that are not texgraph CLI verbs.
ALLOWLISTED_TOOLS = {
    "tools/ontology_check.py",
    "tools/skill_index.py",
    "(none)",  # explicit "this skill drives no tool" marker
}

INDEX_START = "<!-- SKILL-INDEX:START — generated by tools/skill_index.py; do not edit by hand -->"
INDEX_END = "<!-- SKILL-INDEX:END -->"


def _repo_root() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "pyproject.toml").exists():
            return parent
    raise RuntimeError("Cannot locate repo root — no pyproject.toml found.")


def _known_modules(root: Path) -> set[str]:
    mods = {p.name for p in (root / "modules").iterdir() if p.is_dir()}
    mods.add("machinery")
    return mods


def _valid_command_roots(root: Path) -> set[str]:
    """Extract the set of first-level `texgraph <root>` command names from cli.py.

    Catches @app.command(name="x"), add_typer(..., name="x") sub-apps, and
    bare @app.command() (Typer derives the name from the function, underscores
    becoming hyphens). Used to sanity-check skill `tools` entries.
    """
    cli = (root / "backend/core/cli.py").read_text(encoding="utf-8")
    roots: set[str] = set()
    # @app.command(name="x"), @app.command("x"), and @sub_app.command("x")
    roots.update(re.findall(r'\.command\(name="([^"]+)"\)', cli))
    roots.update(re.findall(r'\.command\(\s*"([^"]+)"', cli))
    roots.update(re.findall(r'add_typer\([^,]+,\s*name="([^"]+)"', cli))
    # bare @app.command() \n def foo_bar( -> "foo-bar"
    for m in re.finditer(r'@app\.command\(\)\s*\ndef\s+(\w+)\(', cli):
        roots.add(m.group(1).replace("_", "-"))
    return roots


def _parse_frontmatter(text: str) -> dict | None:
    text = text.lstrip("﻿")  # tolerate a BOM
    m = re.match(r"^---\r?\n(.*?)\r?\n---", text, re.S)
    if not m:
        return None
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return None


def _skill_files(root: Path) -> list[Path]:
    return sorted(
        list((root / "machinery/skills").glob("*/SKILL.md"))
        + list((root / "modules").glob("*/skills/*/SKILL.md"))
    )


def _module_of(path: Path, root: Path) -> str:
    rel = path.relative_to(root).parts
    return "machinery" if rel[0] == "machinery" else rel[1]


def validate(root: Path) -> tuple[list[dict], list[str]]:
    """Return (records, problems)."""
    modules = _known_modules(root)
    roots = _valid_command_roots(root)
    records: list[dict] = []
    problems: list[str] = []

    for sk in _skill_files(root):
        rel = sk.relative_to(root).as_posix()
        fm = _parse_frontmatter(sk.read_text(encoding="utf-8"))
        if fm is None:
            problems.append(f"{rel}: missing or unparseable YAML frontmatter")
            continue
        for field in REQUIRED_FIELDS:
            if field not in fm or fm[field] in (None, "", []):
                problems.append(f"{rel}: frontmatter missing required field `{field}`")

        module = fm.get("module")
        path_module = _module_of(sk, root)
        if module and module != path_module:
            problems.append(
                f"{rel}: frontmatter module `{module}` != path module `{path_module}`"
            )
        if module and module not in modules:
            problems.append(f"{rel}: module `{module}` is not a real module")

        tools = fm.get("tools") or []
        if not isinstance(tools, list):
            problems.append(f"{rel}: `tools` must be a list")
            tools = []
        for tool in tools:
            if tool in ALLOWLISTED_TOOLS:
                continue
            if not str(tool).startswith("texgraph "):
                problems.append(f"{rel}: tool `{tool}` is not a `texgraph` command or allow-listed")
                continue
            cmd_root = str(tool).split()[1]
            if cmd_root not in roots:
                problems.append(f"{rel}: tool `{tool}` -> unknown command `{cmd_root}`")

        records.append(
            {
                "module": path_module,
                "name": fm.get("name", sk.parent.name),
                "description": (fm.get("description") or "").strip(),
                "tools": tools,
                "path": rel,
            }
        )

    skill_names = {r["name"] for r in records}
    problems += _validate_agents(root, modules, roots, skill_names)
    return records, problems


AGENT_FIELDS = ("stage", "screen", "title", "module", "gate", "upstream", "io", "tools", "skills", "system_prompt")


def _validate_agents(root: Path, modules: set[str], roots: set[str], skill_names: set[str]) -> list[str]:
    """Validate framework/agents/<stage>/agent.yaml specs (the runtime agent definitions)."""
    problems: list[str] = []
    agents_dir = root / "framework" / "agents"
    if not agents_dir.exists():
        return problems
    for spec in sorted(agents_dir.glob("*/agent.yaml")):
        rel = spec.relative_to(root).as_posix()
        try:
            data = yaml.safe_load(spec.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError as exc:
            problems.append(f"{rel}: unparseable YAML ({exc})")
            continue
        for field in AGENT_FIELDS:
            if field not in data:
                problems.append(f"{rel}: missing required field `{field}`")
        if data.get("stage") and data["stage"] != spec.parent.name:
            problems.append(f"{rel}: stage `{data['stage']}` != dir `{spec.parent.name}`")
        if data.get("module") and data["module"] not in modules:
            problems.append(f"{rel}: module `{data['module']}` is not a real module")
        io = data.get("io") or {}
        if not isinstance(io, dict) or "receives" not in io or "produces" not in io:
            problems.append(f"{rel}: `io` must define `receives` and `produces`")
        for tool in data.get("tools") or []:
            if not str(tool).startswith("texgraph "):
                problems.append(f"{rel}: tool `{tool}` is not a `texgraph` command")
            elif str(tool).split()[1] not in roots:
                problems.append(f"{rel}: tool `{tool}` -> unknown command `{str(tool).split()[1]}`")
        for sk in data.get("skills") or []:
            if sk not in skill_names:
                problems.append(f"{rel}: skill `{sk}` not found among defined skills")
    return problems


def _trigger(desc: str) -> str:
    """Condense a description to its trigger clause for the index."""
    # Prefer the "Use when/for ..." clause if present.
    m = re.search(r"\bUse (?:when|for)\b(.*)", desc, re.I)
    text = (m.group(0) if m else desc).strip().rstrip(".")
    return (text[:117] + "…") if len(text) > 118 else text


def render_index(records: list[dict], root: Path) -> str:
    modules = _known_modules(root)
    # Stable module order: pipeline DAG, then machinery.
    order = [
        "workspace", "sources", "transcription", "manuscript", "interior",
        "covers", "publication", "release", "studio", "platform", "machinery",
    ]
    order += sorted(m for m in modules if m not in order)

    lines = [
        INDEX_START,
        "",
        "Load **only** the row(s) for the module your classified job targets: open"
        " that skill's `SKILL.md` and use only its listed tools. Do not preload"
        " other modules' skills or the full command surface.",
        "",
        "| Module | Skill | Load it when… | Tools it uses |",
        "|---|---|---|---|",
    ]
    by_mod: dict[str, list[dict]] = {}
    for r in records:
        by_mod.setdefault(r["module"], []).append(r)
    for mod in order:
        for r in sorted(by_mod.get(mod, []), key=lambda x: x["name"]):
            tools = ", ".join(f"`{t}`" for t in r["tools"]) if r["tools"] else "—"
            lines.append(
                f"| `{mod}` | [`{r['name']}`]({_link(r['path'])}) | {_trigger(r['description'])} | {tools} |"
            )
    lines += ["", INDEX_END]
    return "\n".join(lines)


def _link(rel: str) -> str:
    return "../../" + rel if rel.startswith("modules/") or rel.startswith("machinery/") else rel


def write_index(root: Path, records: list[dict]) -> bool:
    onto = root / "README.md"
    text = onto.read_text(encoding="utf-8")
    block = render_index(records, root)
    if INDEX_START in text and INDEX_END in text:
        new = re.sub(
            re.escape(INDEX_START) + r".*?" + re.escape(INDEX_END),
            block.replace("\\", "\\\\"),
            text,
            flags=re.S,
        )
    else:
        problems_marker = "\n## Skill & Tool Loading Contract\n"
        if problems_marker in text:
            new = text.replace(problems_marker, problems_marker + "\n" + block + "\n", 1)
        else:
            new = text.rstrip() + "\n\n" + block + "\n"
    changed = new != text
    if changed:
        onto.write_text(new, encoding="utf-8")
    return changed


def current_index(root: Path) -> str:
    text = (root / "README.md").read_text(encoding="utf-8")
    m = re.search(re.escape(INDEX_START) + r".*?" + re.escape(INDEX_END), text, re.S)
    return m.group(0) if m else ""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="Regenerate the index in README.md.")
    ap.add_argument("--check", action="store_true", help="Exit nonzero on any contract violation or index drift.")
    args = ap.parse_args()
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except Exception:
        pass
    root = _repo_root()

    records, problems = validate(root)

    for p in problems:
        print(f"  [X] {p}")
    print(f"\n{len(records)} skill(s) scanned, {len(problems)} problem(s).")

    if args.write:
        changed = write_index(root, records)
        print("Index regenerated." if changed else "Index already up to date.")
        return 1 if problems else 0

    drift = render_index(records, root) != current_index(root)
    if args.check:
        if problems:
            print("\nContract violations above — fix the SKILL.md frontmatter.")
            return 1
        if drift:
            print("\nIndex is out of date — run: python tools/skill_index.py --write")
            return 1
        print("Skill & tool loading contract OK; index in sync.")
        return 0

    if drift:
        print("\n(index out of date — run with --write)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
